config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :genres
  resources :directors
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
  belongs_to :genre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :update, :destroy]

  def index
    @directors = Director.all
  end

  def show
    @movies = @director.movies
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.create(director_params)
    if @director.save
      redirect_to @director, notice: 'Director was successfully created.'
    else
      render :new
    end
  end

  def update
    if @director.update(director_params)
      redirect_to @director, notice: 'Director was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url, notice: 'Director was successfully destroyed.'
  end

  private
  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params.require(:director).permit(:name, :nationality, :birth_date, :favorite_genre)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create(genre_params)
    if @genre.save
      redirect_to @genre, notice: 'Genre was successfully created.'
    else
      render :new
    end
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: 'Genre was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, notice: 'Genre was successfully destroyed.'
  end

  private
  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.select(:id, :title, :release_year)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to movies_url, notice: 'Movie was successfully destroyed.'
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :release_year, :synopsis, :country, :duration, :director_id, :genre_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/directors/edit.html.erb
<h1>Editar Diretor</h1>

<%= form_with(model: @director, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :nationality %>
  <%= form.text_field :nationality %>

  <%= form.label :birth_date %>
  <%= form.date_field :birth_date %>

  <%= form.label :favorite_genre_name, "Gênero Favorito" %>
  <%= form.select :favorite_genre_name, Genre.all.map { |genre| [genre.name, genre.name] }, { include_blank: true } %>

  <%= form.submit %>
<% end %>

app/views/directors/index.html.erb
<h1>Listagem de Diretores</h1>


<div class="director-list">
  <% @directors.each do |director| %>
    <%= link_to director_path(director), class: 'genre-item' do %>
      <%= director.name %>
    <% end %>
  <% end %>
</div>
<br>
<br>
<%= link_to 'Adicionar Diretor', new_director_path, class:'add-button' %>

app/views/directors/new.html.erb
<h1>Novo Diretor</h1>

<%= form_with(model: @director, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :nationality %>
  <%= form.text_field :nationality %>

  <%= form.label :birth_date %>
  <%= form.date_field :birth_date %>

  <%#= form.label :favorite_genre, "Gênero Favorito" %>
  <%#= form.text_field :favorite_genre %>


  <%= form.label :favorite_genre, "Gênero Favorito" %>
  <%= form.select :favorite_genre, Genre.all.map { |genre| [genre.name, genre.name] }, { include_blank: true } %>

  <%= form.submit %>

<% end %>

<br>
<br>

<%= link_to 'Voltar', :back, class: 'back-button' %>

app/views/directors/show.html.erb
<h1>Detalhes do Diretor</h1>

<p><strong>Nome:</strong> <%= @director.name %></p>
<p><strong>Nacionalidade:</strong> <%= @director.nationality %></p>
<p><strong>Data de Nascimento:</strong> <%= @director.birth_date %></p>
<p><strong>Gênero Favorito:</strong> <%= @director.favorite_genre %></p>

<h2>Filmes Dirigidos por Este Diretor</h2>
<ul>
  <% @director.movies.each do |movie| %>
    <li><%= movie.title %> (Ano: <%= movie.release_year %>)</li>
  <% end %>
</ul>
<br>
<br>
<%= link_to 'Editar', edit_director_path(@director), class: 'edit-button' %> |
<%= link_to 'Voltar', directors_path, class: 'back-button' %>

app/views/genres/edit.html.erb
<h1>Editar Gênero</h1>

<%= form_with(model: @genre, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit %>
<% end %>

app/views/genres/index.html.erb
<h1>Listagem de Gêneros</h1>

<div class="genre-list">
  <% @genres.each do |genre| %>
    <%= link_to genre_path(genre), class: 'genre-item' do %>
      <%= genre.name %>
    <% end %>
  <% end %>
</div>
<br>
<br>
<%= link_to 'Adicionar Gênero', new_genre_path, class: 'add-button' %>

app/views/genres/new.html.erb
<h1>Novo Gênero</h1>

<%= form_with(model: @genre, url: genres_path, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit %>
<% end %>

<br>
<br>

<%= link_to 'Voltar', :back, class: 'back-button' %>

app/views/genres/show.html.erb
<h1>Detalhes do Gênero</h1>

<p><strong>Nome:</strong> <%= @genre.name %></p>

<h2>Filmes deste Gênero</h2>
<ul>
  <% @genre.movies.each do |movie| %>
    <li><%= movie.title %></li>
  <% end %>
</ul>

<br>
<br>
<%= link_to 'Editar', edit_genre_path(@genre), class: 'edit-button' %>
<%= link_to 'Voltar', genres_path, class: 'back-button' %>

app/views/home/index.html.erb
<h1>Bem-vindo ao meu catalogo de filme! :)</h1>

<div class="btn-group-vertical">
  <%= link_to 'Gêneros', genres_path, class: 'btn btn-primary btn-lg mb-3' %>
  <%= link_to 'Filmes', movies_path, class: 'btn btn-primary btn-lg mb-3' %>
  <%= link_to 'Diretores', directors_path, class: 'btn btn-primary btn-lg mb-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatalogoDeFilmes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to 'Home', root_path, class: 'home-button' %>
  <%= yield %>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>Editar Filme</h1>

<%= form_with(model: @movie, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :release_year %>
  <%= form.number_field :release_year %>

  <%= form.label :synopsis %>
  <%= form.text_area :synopsis %>

  <%= form.label :country %>
  <%= form.text_field :country %>

  <%= form.label :duration %>
  <%= form.number_field :duration %>

  <%= form.label :director_id, "Diretor" %>
  <%= form.collection_select :director_id, Director.all, :id, :name %>

  <%= form.label :genre_id, "Gênero" %>
  <%= form.collection_select :genre_id, Genre.all, :id, :name %>

  <%= form.submit %>
<% end %>

app/views/movies/index.html.erb
<h1>Listagem de Filmes</h1>


<div class="movie-list">
  <% @movies.each do |movie| %>
    <%= link_to movie_path(movie), class: 'genre-item' do %>
      <%= movie.title %>
    <% end %>
  <% end %>
</div>

<br>
<br>
<%= link_to 'Adicionar Filme', new_movie_path, class: 'add-button' %>

app/views/movies/new.html.erb
<h1>Novo Filme</h1>

<%= form_with(model: @movie, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :release_year %>
  <%= form.number_field :release_year %>

  <%= form.label :synopsis %>
  <%= form.text_area :synopsis %>

  <%= form.label :country %>
  <%= form.text_field :country %>

  <%= form.label :duration %>
  <%= form.number_field :duration %>

  <%= form.label :director_id, "Diretor" %>
  <%= form.collection_select :director_id, Director.all, :id, :name %>

  <%= form.label :genre_id, "Gênero" %>
  <%= form.collection_select :genre_id, Genre.all, :id, :name %>

  <%= form.submit %>
<% end %>

<br>
<br>

<%= link_to 'Voltar', :back, class: 'back-button' %>

app/views/movies/show.html.erb
<h1>Detalhes do Filme</h1>

<p><strong>Título:</strong> <%= @movie.title %></p>
<p><strong>Ano de Lançamento:</strong> <%= @movie.release_year %></p>
<p><strong>Sinopse:</strong> <%= @movie.synopsis %></p>
<p><strong>País de Origem:</strong> <%= @movie.country %></p>
<p><strong>Duração:</strong> <%= @movie.duration %> minutos</p>
<p><strong>Diretor:</strong> <%= @movie.director.name %></p>
<p><strong>Gênero:</strong> <%= @movie.genre.name %></p>
<br>
<br>
<%= link_to 'Editar', edit_movie_path(@movie), class: 'edit-button' %> |
<%= link_to 'Voltar', movies_path, class: 'back-button' %>